export * from './api-requests.service';
export * from './aluno.service';
export * from './turma.service';
export * from './disciplina.service';
export * from './nota.service';
export * from './responsavel-financeiro.service';
export * from './matricula.service';
export * from './turma-disciplina.service';
export * from './estatisticas.service';
